apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: us-central1-docker.pkg.dev/my-project-63678/my-repo/my-app
    newTag: latest # Cloud Build will overwrite this automatically